FROM node:14.14.0-alpine AS builder
WORKDIR "/app"
COPY ./package.json ./
RUN npm install
COPY . . 
EXPOSE 4200
# CMD ["npm", "run", "start"]
CMD npm start --host 0.0.0.0 --disable-host-check 

# FROM nginx
# EXPOSE 4200
# COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
# COPY --from=builder /src/app/build /usr/share/nginx/html